# docker-compose.yml

version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; sleep 5; cd src/sreality_display_api; uvicorn main:app --host 0.0.0.0'
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=srealitky
      - POSTGRES_PASSWORD=srealitky
      - POSTGRES_DB=srealitky
      - POSTGRES_PORT=5432
    depends_on:
      - db
    #env_file:
    #  - ./.env
    networks:
      - practice
    links:
      - db

  db:
    image: 'postgres'
    restart: always
    volumes:
      - db:/var/lib/postgresql/data/
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - '5432:5432'
    expose:
      - 5432
    environment:
      - POSTGRES_USER=srealitky
      - POSTGRES_PASSWORD=srealitky
      - POSTGRES_DB=srealitky
    networks:
      - practice

  scrapper:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; cd src/sreality_scrapper; scrapy crawl sreality_image'
    volumes:
      - .:/app
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=srealitky
      - POSTGRES_PASSWORD=srealitky
      - POSTGRES_DB=srealitky
    depends_on:
      - db
    links:
      - db
    #env_file:
    #  - ./.env
    networks:
      - practice

volumes:
  db:
    driver: local

networks:
  practice: